import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Pipefy</title>
				<meta name="description" content="Generated by create vue app" />
			</Head>
		</div>
	);
}
