import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Pipefy</title>
				<meta name="description" content="Generated by create vue app" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap"
					rel="stylesheet"
				></link>
			</Head>
		</div>
	);
}
